### ISSUE TITLE
problem with server

### ISSUE THREAD

**Issue by protossknight** [samolego/ChestRefill#1]
hi the mod crashes my server i attached the log file
[crash-2022-02-21_15.27.10-fml.txt](https://github.com/samolego/ChestRefill/files/8112226/crash-2022-02-21_15.27.10-fml.txt)

**Comment by samolego** [comment]
Seems like I've messed mods.toml (again). Thanks for report!

**Comment by protossknight** [comment]
no problem

**Comment by samolego** [comment]
Could you try latest build from actions?

**Comment by protossknight** [comment]
tried it and didnt crash the server all going good

**Comment by samolego** [comment]
Ok, will release it then.
