### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by SulpherStaer** [samolego/ChestRefill#2]
Do you have any intention of updating this mod to 1.19? It is exactly what I am looking for, and really want to use on my server that has a tiny world border.

**Comment by samolego** [comment]
Soon (tm)

**Comment by SulpherStaer** [comment]
ty - I'll await the fabric version release. thanks for making this addon. I'd throw money your way if you had support enabled or something similar.

**Comment by samolego** [comment]
there's https://samolego.github.io/donate 😉
