### ISSUE TITLE
Doesn't work in the End

### ISSUE THREAD

**Issue by eVic75** [samolego/ChestRefill#4]
Works great in the Overworld and in the Nether, doesn't work in the End: chests in the end cities do not refill. 
Minecraft 1.19. Used mods:

fabric-api-0.55.3+1.19
cloth-api-4.0.65
cloth-config-7.0.72-fabric
chestrefill-1.1.0-fabric

No other mods, no datapacks.

**Comment by samolego** [comment]
Humm, mod isn't dimension specific, do you have any special rules set up for end loot tables? Are you sure chests weren't looted previously?

**Comment by eVic75** [comment]
I checked on freshly created worlds so the chests were never looted. My config file:
` {
  "defaultProperties": {
    "randomize_loot_seed": true,
    "allow_reloot_without_permission": true,
    "max_refills": -1,
    "refill_non_empty": false,
    "min_wait_time": 15
  },
  "// Map to override above config for certain loot tables only.": "",
  "lootModifierMap": {
    "sample_mod:chests/custom_loot_table": {
      "randomize_loot_seed": true,
      "allow_reloot_without_permission": false,
      "max_refills": 5,
      "refill_non_empty": false,
      "min_wait_time": 14400
    },
    "//minecraft:chests/igloo_chest": {
      "randomize_loot_seed": true,
      "allow_reloot_without_permission": false,
      "max_refills": 5,
      "refill_non_empty": false,
      "min_wait_time": 14400
    }
  }
}`

Works perfectly in Overworld and Nether.

**Comment by eVic75** [comment]
When I put a chest in the End (also in the Nether and Overworld) using the command:

`setblock ~ ~ ~ minecraft:chest{ChestRefill: {RefillCounter: 0, SavedLootTable: "minecraft:chests/end_city_treasure", CustomValues: {AllowReloot: 1b, MaxRefills: -1, MinWaitTime: 15}}}`

everything works, chest refills.
Maybe this is a problem with name **end_city_treasure** ?

**Comment by samolego** [comment]
> Maybe this is a problem with name **end_city_treasure**?

Not sure what do you mean, but mod just checks the config for any overrides, it doesn't check loot table names by itself.

**Comment by eVic75** [comment]
You guessed very well what I meant :) Now I know, it doesn't check loot table names. 
It looks as if the mod treats naturally generated chests in the End like regular chests placed by the player.
Do not be offended, I ask to be sure: have you checked your mod in the End on Minecraft 1.19 Fabric? Your chests refill?

**Comment by samolego** [comment]
Whoops, didn't mean to close it.

I'll check it on my end.

**Comment by samolego** [comment]
Confirmed, chests don't get refilled here as well. What's even more strange, if I pick up the block using ctrl+middle click (to get the block with nbt data) it does get refilled

**Comment by eVic75** [comment]
Indeed, it's strange :) Probably Mojang broke something as usual. ;)
 I'm sure you can handle this problem. It is an excellent mod and it would be a pity that it would not be fully operational.

**Comment by eVic75** [comment]
And now the surprise: the mod works perfectly fine in MC version 1.19.1 :)
So that's Mojang's fault :)
It's an excellent mod, thank you for your work.

Best regards.

**Comment by samolego** [comment]
Huh, what, wasn't expecting that :P. Glad to see it resolved though :).

**Comment by eVic75** [comment]
Hi samolego :)
I am forced to reopen this thread.
First of all, it will be nice to meet you again, samolego. :)
Your mod works in version 1.20.1 (with a little modification to the fabric.mod.json file of course ;) ) but the old problem is back: chests in the End don't refill. You wrote in the description:

works on any container extending `RandomizableContainerBlockEntity`.

Maybe the chests in the End are not "`RandomizableContainerBlockEntity`" in 1.20 MC version? And here is the problem?

Are you planning to update the mod to version 1.20?

Best regards
