### ISSUE TITLE
Trying to build both the latest commit and the latest release fails

### ISSUE THREAD

**Issue by ArkoSammy12** [samolego/ChestRefill#5]
Hello. I'm trying to build the Chest Refill mods, but the build process is failing.

For the latest release (Chest Refill 1.1.1 for 1.20.1), it says it is using deprecated Gradle features.

For the latest commit, it says it could not receive a message from the daemon. 

Is there any way I can fix this?

Edit: For some reason after trying to build the latest release for the second time, it worked. Closing the issue now

**Comment by samolego** [comment]
Welcome to the nightmare that is gradle
