### ISSUE TITLE
1.20.1 jar file

### ISSUE THREAD

**Issue by MokusProf** [samolego/ChestRefill#8]
I would greatly appreciate if you could build a jar file. I tried myself but since i mostly don't know what i should be doing it didn't work.

**Comment by samolego** [comment]
Mod will probably need updating, that's why it doesn't build.

Though I think a new mod has come with exactly same purpose

**Comment by MokusProf** [comment]
Oh do you know what the new mod name is? I was trying to find similar mods but i haven't had the luck.

**Comment by samolego** [comment]
it was mentioned in fabric discord, not sure of the name :(

**Comment by MokusProf** [comment]
Too bad but thanks for answering me. Might ask around there.
